services:
  simple-nginx-prod:
    container_name: simple_nginx_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - appnetwork
    restart: unless-stopped

networks:
  appnetwork:
    name: appnetwork
    driver: bridge
