services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm_app_dev
    restart: unless-stopped
    ports:
      - '8081:80'
      - '4443:443'
      - '8082:81'
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - appnetwork

  simple-nginx-dev:
    container_name: simple_nginx_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      - appnetwork
    restart: unless-stopped

networks:
  appnetwork:
    name: appnetwork
    driver: bridge
