name: Deploy to dev on push

on:
  push:
    branches: [ dev ]   

jobs:
  deploy-dev:
    name: Build and update dev server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}      
          username: ${{ secrets.SERVER_USER }}  
          key: ${{ secrets.SSH_PRIVATE_KEY }}   
          port: 22
          script: |
            
            cd /opt/nginx-proxy-manager/first-repository

            # переключаемся на ветку dev
            git fetch --all
            git reset --hard origin/dev
            git checkout dev

            docker compose build

            # Запускаем контейнеры (если уже запущены — перезапустятся с новыми образами)
            docker compose up -d

            # Очищаем старые образы (опционально)
            docker system prune -f
