name: Deploy to dev site

on:
  push:
    branches: [dev]  

jobs:
  deploy:
    name: Deploy dev version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to dev folder on server
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/nginx-proxy-manager/dev-repository
            
            git fetch --all
            git reset --hard origin/dev
            git checkout dev
            git pull origin dev
                       
            docker compose -f docker-compose.dev.yml -p dev build
            docker compose -f docker-compose.dev.yml -p dev up -d
            docker system prune -f
