name: On-server Deploy

on:
  push:
    branches:
      - main

env:
  TEST_TAG: myapp:test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test built image
        run: |
          docker compose up -d
          sleep 3
          docker compose ps | grep "Up" || exit 1
          docker compose down

      - name: Deploy via SSH (build on server)
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /opt/nginx-proxy-manager/first-repository
            git pull origin main
            docker compose build
            docker compose up -d
            docker system prune -f
